export const data = [
  {
    "Announcement Date": "01/01/2021",
    "Completion date": "06/06/21",
    "Deal type": "M&A",
    "Buyer/in-licenser/investor": "Pfizer",
    "Country of Buyer": "US",
    Region: "US",
    "Target/partner/investee": "Trillium Therapeutics",
    "Country of Target": "US",
    "Private/Public (Target)": "Public",
    "Premium paid (if Public)": "...0",
    "PE/VC backed (Y/N)": "...0",
    "Total deal value($m)": "2260",
    "Upfront value ($m)": "2260",
    "Milestones/earnouts ($m)": "...0",
    "VC investment": "...0",
    "Therapy Area(s)": "Oncology [haematological]",
    "Drug type (biologic/small molecule/vaccine)": "Biologic",
    "Technology(s)": "mAbs",
    "Stage of lead product": "Phase Ib/II",
    "Lead product(s)": "TTI-662, TTI-621",
    "Indication(s)": "Multiple tumour types",
    "Mechanism of action": "anti-CD47",
    "": "...0",
    "Potential first-in-class drug? (Y/N)": "Y",
    "Geographic remit of deal ": "Global",
    "Deal structure": "Acquisition",
    "Milestone dates": "...0",
    "Financial advisors": "Bank of America, Centerview Partners",
    "Legal advisors":
      "Ropes & Gray; Norton Rose Fulbright Canada; Goodwin Procter; Baker McKenzie",
    "Number of other interested parties (if M&A)": "...0",
    "Related FW content": "...0",
    "Post-deal updates": "...0"
  },
  {
    "Announcement Date": "...1",
    "Completion date": "...1",
    "Deal type": "...1",
    "Buyer/in-licenser/investor": "Pfizer",
    "Country of Buyer": "...1",
    Region: "...1",
    "Target/partner/investee": "xxx",
    "Country of Target": "...1",
    "Private/Public (Target)": "...1",
    "Premium paid (if Public)": "...1",
    "PE/VC backed (Y/N)": "...1",
    "Total deal value($m)": "...1",
    "Upfront value ($m)": "...1",
    "Milestones/earnouts ($m)": "...1",
    "VC investment": "...1",
    "Therapy Area(s)": "...1",
    "Drug type (biologic/small molecule/vaccine)": "...1",
    "Technology(s)": "...1",
    "Stage of lead product": "...1",
    "Lead product(s)": "...1",
    "Indication(s)": "...1",
    "Mechanism of action": "...1",
    "": "...1",
    "Potential first-in-class drug? (Y/N)": "...1",
    "Geographic remit of deal ": "...1",
    "Deal structure": "...1",
    "Milestone dates": "...1",
    "Financial advisors": "...1",
    "Legal advisors": "...1",
    "Number of other interested parties (if M&A)": "...1",
    "Related FW content": "...1",
    "Post-deal updates": "...1"
  },
  {
    "Announcement Date": "...2",
    "Completion date": "...2",
    "Deal type": "...2",
    "Buyer/in-licenser/investor": "Pfizer",
    "Country of Buyer": "...2",
    Region: "...2",
    "Target/partner/investee": "...2",
    "Country of Target": "...2",
    "Private/Public (Target)": "...2",
    "Premium paid (if Public)": "...2",
    "PE/VC backed (Y/N)": "...2",
    "Total deal value($m)": "...2",
    "Upfront value ($m)": "...2",
    "Milestones/earnouts ($m)": "...2",
    "VC investment": "...2",
    "Therapy Area(s)": "...2",
    "Drug type (biologic/small molecule/vaccine)": "...2",
    "Technology(s)": "...2",
    "Stage of lead product": "...2",
    "Lead product(s)": "...2",
    "Indication(s)": "...2",
    "Mechanism of action": "...2",
    "": "...2",
    "Potential first-in-class drug? (Y/N)": "...2",
    "Geographic remit of deal ": "...2",
    "Deal structure": "...2",
    "Milestone dates": "...2",
    "Financial advisors": "...2",
    "Legal advisors": "...2",
    "Number of other interested parties (if M&A)": "...2",
    "Related FW content": "...2",
    "Post-deal updates": "...2"
  },
  {
    "Announcement Date": "...3",
    "Completion date": "...3",
    "Deal type": "...3",
    "Buyer/in-licenser/investor": "Pfizer",
    "Country of Buyer": "...3",
    Region: "...3",
    "Target/partner/investee": "...3",
    "Country of Target": "...3",
    "Private/Public (Target)": "...3",
    "Premium paid (if Public)": "...3",
    "PE/VC backed (Y/N)": "...3",
    "Total deal value($m)": "...3",
    "Upfront value ($m)": "...3",
    "Milestones/earnouts ($m)": "...3",
    "VC investment": "...3",
    "Therapy Area(s)": "...3",
    "Drug type (biologic/small molecule/vaccine)": "...3",
    "Technology(s)": "...3",
    "Stage of lead product": "...3",
    "Lead product(s)": "...3",
    "Indication(s)": "...3",
    "Mechanism of action": "...3",
    "": "...3",
    "Potential first-in-class drug? (Y/N)": "...3",
    "Geographic remit of deal ": "...3",
    "Deal structure": "...3",
    "Milestone dates": "...3",
    "Financial advisors": "...3",
    "Legal advisors": "...3",
    "Number of other interested parties (if M&A)": "...3",
    "Related FW content": "...3",
    "Post-deal updates": "...3"
  },
  {
    "Announcement Date": "...4",
    "Completion date": "...4",
    "Deal type": "Licensing collaboration",
    "Buyer/in-licenser/investor": "Novartis",
    "Country of Buyer": "...4",
    Region: "...4",
    "Target/partner/investee": "Ada Health",
    "Country of Target": "...4",
    "Private/Public (Target)": "...4",
    "Premium paid (if Public)": "...4",
    "PE/VC backed (Y/N)": "...4",
    "Total deal value($m)": "Undisclosed",
    "Upfront value ($m)": "...4",
    "Milestones/earnouts ($m)": "...4",
    "VC investment": "...4",
    "Therapy Area(s)": "Immunology",
    "Drug type (biologic/small molecule/vaccine)": "...4",
    "Technology(s)": "Symptom assessment",
    "Stage of lead product": "...4",
    "Lead product(s)": "Ada symptom checker",
    "Indication(s)": "...4",
    "Mechanism of action": "n/a",
    "": "...4",
    "Potential first-in-class drug? (Y/N)": "...4",
    "Geographic remit of deal ": "Global",
    "Deal structure": "...4",
    "Milestone dates": "...4",
    "Financial advisors": "...4",
    "Legal advisors": "...4",
    "Number of other interested parties (if M&A)": "...4",
    "Related FW content": "...4",
    "Post-deal updates": "...4"
  },
  {
    "Announcement Date": "...5",
    "Completion date": "...5",
    "Deal type": "...5",
    "Buyer/in-licenser/investor": "Novartis",
    "Country of Buyer": "...5",
    Region: "...5",
    "Target/partner/investee": "xxxx",
    "Country of Target": "...5",
    "Private/Public (Target)": "...5",
    "Premium paid (if Public)": "...5",
    "PE/VC backed (Y/N)": "...5",
    "Total deal value($m)": "...5",
    "Upfront value ($m)": "...5",
    "Milestones/earnouts ($m)": "...5",
    "VC investment": "...5",
    "Therapy Area(s)": "...5",
    "Drug type (biologic/small molecule/vaccine)": "...5",
    "Technology(s)": "...5",
    "Stage of lead product": "...5",
    "Lead product(s)": "...5",
    "Indication(s)": "...5",
    "Mechanism of action": "...5",
    "": "...5",
    "Potential first-in-class drug? (Y/N)": "...5",
    "Geographic remit of deal ": "...5",
    "Deal structure": "...5",
    "Milestone dates": "...5",
    "Financial advisors": "...5",
    "Legal advisors": "...5",
    "Number of other interested parties (if M&A)": "...5",
    "Related FW content": "...5",
    "Post-deal updates": "...5"
  },
  {
    "Announcement Date": "...6",
    "Completion date": "...6",
    "Deal type": "...6",
    "Buyer/in-licenser/investor": "Novartis",
    "Country of Buyer": "...6",
    Region: "...6",
    "Target/partner/investee": "...6",
    "Country of Target": "...6",
    "Private/Public (Target)": "...6",
    "Premium paid (if Public)": "...6",
    "PE/VC backed (Y/N)": "...6",
    "Total deal value($m)": "...6",
    "Upfront value ($m)": "...6",
    "Milestones/earnouts ($m)": "...6",
    "VC investment": "...6",
    "Therapy Area(s)": "...6",
    "Drug type (biologic/small molecule/vaccine)": "...6",
    "Technology(s)": "...6",
    "Stage of lead product": "...6",
    "Lead product(s)": "...6",
    "Indication(s)": "...6",
    "Mechanism of action": "...6",
    "": "...6",
    "Potential first-in-class drug? (Y/N)": "...6",
    "Geographic remit of deal ": "...6",
    "Deal structure": "...6",
    "Milestone dates": "...6",
    "Financial advisors": "...6",
    "Legal advisors": "...6",
    "Number of other interested parties (if M&A)": "...6",
    "Related FW content": "...6",
    "Post-deal updates": "...6"
  },
  {
    "Announcement Date": "...7",
    "Completion date": "...7",
    "Deal type": "Licensing collaboration",
    "Buyer/in-licenser/investor": "Roche",
    "Country of Buyer": "...7",
    Region: "...7",
    "Target/partner/investee": "Adaptimmune",
    "Country of Target": "...7",
    "Private/Public (Target)": "...7",
    "Premium paid (if Public)": "...7",
    "PE/VC backed (Y/N)": "...7",
    "Total deal value($m)": "3300",
    "Upfront value ($m)": "150",
    "Milestones/earnouts ($m)": "3150",
    "VC investment": "...7",
    "Therapy Area(s)": "Oncology  ",
    "Drug type (biologic/small molecule/vaccine)": "...7",
    "Technology(s)": "T-cell therapy",
    "Stage of lead product": "Pre-clinical",
    "Lead product(s)": "n/a",
    "Indication(s)": "Multiple tumour types",
    "Mechanism of action": "Allogeneic T-cells therapies",
    "": "...7",
    "Potential first-in-class drug? (Y/N)": "...7",
    "Geographic remit of deal ":
      'Global (Adaptimmune has the right to opt in to a 50/50 US profit/cost share on "off-the-shelf" products.',
    "Deal structure": "...7",
    "Milestone dates": "...7",
    "Financial advisors": "...7",
    "Legal advisors": "...7",
    "Number of other interested parties (if M&A)": "...7",
    "Related FW content": "...7",
    "Post-deal updates": "...7"
  },
  {
    "Announcement Date": "...8",
    "Completion date": "...8",
    "Deal type": "M&A",
    "Buyer/in-licenser/investor": "Sanofi",
    "Country of Buyer": "...8",
    Region: "...8",
    "Target/partner/investee": "Translate Bio",
    "Country of Target": "...8",
    "Private/Public (Target)": "...8",
    "Premium paid (if Public)": "...8",
    "PE/VC backed (Y/N)": "...8",
    "Total deal value($m)": "3200",
    "Upfront value ($m)": "3200",
    "Milestones/earnouts ($m)": "...8",
    "VC investment": "...8",
    "Therapy Area(s)": "Various",
    "Drug type (biologic/small molecule/vaccine)": "...8",
    "Technology(s)": "mRNA (vaccines/therapeutics)",
    "Stage of lead product": "Phase I/II",
    "Lead product(s)": "MRT5500",
    "Indication(s)": "COVID-19",
    "Mechanism of action": "mRNA vaccine",
    "": "...8",
    "Potential first-in-class drug? (Y/N)": "...8",
    "Geographic remit of deal ": "Global",
    "Deal structure": "Acquisition",
    "Milestone dates": "...8",
    "Financial advisors":
      "Morgan Stanley, Centerview Partners, Evercore, MTS Health Partners",
    "Legal advisors":
      "Weil, Gotshal & Manges; Paul, Weiss, Rifkind, Wharton & Garrison",
    "Number of other interested parties (if M&A)": "...8",
    "Related FW content": "...8",
    "Post-deal updates": "...8"
  },
  {
    "Announcement Date": "...9",
    "Completion date": "...9",
    "Deal type": "...9",
    "Buyer/in-licenser/investor": "Merck",
    "Country of Buyer": "...9",
    Region: "...9",
    "Target/partner/investee": "...9",
    "Country of Target": "...9",
    "Private/Public (Target)": "...9",
    "Premium paid (if Public)": "...9",
    "PE/VC backed (Y/N)": "...9",
    "Total deal value($m)": "...9",
    "Upfront value ($m)": "...9",
    "Milestones/earnouts ($m)": "...9",
    "VC investment": "...9",
    "Therapy Area(s)": "...9",
    "Drug type (biologic/small molecule/vaccine)": "...9",
    "Technology(s)": "...9",
    "Stage of lead product": "...9",
    "Lead product(s)": "...9",
    "Indication(s)": "...9",
    "Mechanism of action": "...9",
    "": "...9",
    "Potential first-in-class drug? (Y/N)": "...9",
    "Geographic remit of deal ": "...9",
    "Deal structure": "...9",
    "Milestone dates": "...9",
    "Financial advisors": "...9",
    "Legal advisors": "...9",
    "Number of other interested parties (if M&A)": "...9",
    "Related FW content": "...9",
    "Post-deal updates": "...9"
  },
  {
    "Announcement Date": "...10",
    "Completion date": "...10",
    "Deal type": "...10",
    "Buyer/in-licenser/investor": "Gilead",
    "Country of Buyer": "...10",
    Region: "...10",
    "Target/partner/investee": "...10",
    "Country of Target": "...10",
    "Private/Public (Target)": "...10",
    "Premium paid (if Public)": "...10",
    "PE/VC backed (Y/N)": "...10",
    "Total deal value($m)": "...10",
    "Upfront value ($m)": "...10",
    "Milestones/earnouts ($m)": "...10",
    "VC investment": "...10",
    "Therapy Area(s)": "...10",
    "Drug type (biologic/small molecule/vaccine)": "...10",
    "Technology(s)": "...10",
    "Stage of lead product": "...10",
    "Lead product(s)": "...10",
    "Indication(s)": "...10",
    "Mechanism of action": "...10",
    "": "...10",
    "Potential first-in-class drug? (Y/N)": "...10",
    "Geographic remit of deal ": "...10",
    "Deal structure": "...10",
    "Milestone dates": "...10",
    "Financial advisors": "...10",
    "Legal advisors": "...10",
    "Number of other interested parties (if M&A)": "...10",
    "Related FW content": "...10",
    "Post-deal updates": "...10"
  },
  {
    "Announcement Date": "...11",
    "Completion date": "...11",
    "Deal type": "...11",
    "Buyer/in-licenser/investor": "J&J",
    "Country of Buyer": "...11",
    Region: "...11",
    "Target/partner/investee": "...11",
    "Country of Target": "...11",
    "Private/Public (Target)": "...11",
    "Premium paid (if Public)": "...11",
    "PE/VC backed (Y/N)": "...11",
    "Total deal value($m)": "...11",
    "Upfront value ($m)": "...11",
    "Milestones/earnouts ($m)": "...11",
    "VC investment": "...11",
    "Therapy Area(s)": "...11",
    "Drug type (biologic/small molecule/vaccine)": "...11",
    "Technology(s)": "...11",
    "Stage of lead product": "...11",
    "Lead product(s)": "...11",
    "Indication(s)": "...11",
    "Mechanism of action": "...11",
    "": "...11",
    "Potential first-in-class drug? (Y/N)": "...11",
    "Geographic remit of deal ": "...11",
    "Deal structure": "...11",
    "Milestone dates": "...11",
    "Financial advisors": "...11",
    "Legal advisors": "...11",
    "Number of other interested parties (if M&A)": "...11",
    "Related FW content": "...11",
    "Post-deal updates": "...11"
  },
  {
    "Announcement Date": "...12",
    "Completion date": "...12",
    "Deal type": "...12",
    "Buyer/in-licenser/investor": "GSK",
    "Country of Buyer": "...12",
    Region: "...12",
    "Target/partner/investee": "...12",
    "Country of Target": "...12",
    "Private/Public (Target)": "...12",
    "Premium paid (if Public)": "...12",
    "PE/VC backed (Y/N)": "...12",
    "Total deal value($m)": "...12",
    "Upfront value ($m)": "...12",
    "Milestones/earnouts ($m)": "...12",
    "VC investment": "...12",
    "Therapy Area(s)": "...12",
    "Drug type (biologic/small molecule/vaccine)": "...12",
    "Technology(s)": "...12",
    "Stage of lead product": "...12",
    "Lead product(s)": "...12",
    "Indication(s)": "...12",
    "Mechanism of action": "...12",
    "": "...12",
    "Potential first-in-class drug? (Y/N)": "...12",
    "Geographic remit of deal ": "...12",
    "Deal structure": "...12",
    "Milestone dates": "...12",
    "Financial advisors": "...12",
    "Legal advisors": "...12",
    "Number of other interested parties (if M&A)": "...12",
    "Related FW content": "...12",
    "Post-deal updates": "...12"
  },
  {
    "Announcement Date": "...13",
    "Completion date": "...13",
    "Deal type": "...13",
    "Buyer/in-licenser/investor": "AstraZeneca",
    "Country of Buyer": "...13",
    Region: "...13",
    "Target/partner/investee": "...13",
    "Country of Target": "...13",
    "Private/Public (Target)": "...13",
    "Premium paid (if Public)": "...13",
    "PE/VC backed (Y/N)": "...13",
    "Total deal value($m)": "...13",
    "Upfront value ($m)": "...13",
    "Milestones/earnouts ($m)": "...13",
    "VC investment": "...13",
    "Therapy Area(s)": "...13",
    "Drug type (biologic/small molecule/vaccine)": "...13",
    "Technology(s)": "...13",
    "Stage of lead product": "...13",
    "Lead product(s)": "...13",
    "Indication(s)": "...13",
    "Mechanism of action": "...13",
    "": "...13",
    "Potential first-in-class drug? (Y/N)": "...13",
    "Geographic remit of deal ": "...13",
    "Deal structure": "...13",
    "Milestone dates": "...13",
    "Financial advisors": "...13",
    "Legal advisors": "...13",
    "Number of other interested parties (if M&A)": "...13",
    "Related FW content": "...13",
    "Post-deal updates": "...13"
  },
  {
    "Announcement Date": "...14",
    "Completion date": "...14",
    "Deal type": "Product in-licensing ",
    "Buyer/in-licenser/investor": "AbbVie",
    "Country of Buyer": "...14",
    Region: "...14",
    "Target/partner/investee": "Regenxbio",
    "Country of Target": "...14",
    "Private/Public (Target)": "...14",
    "Premium paid (if Public)": "...14",
    "PE/VC backed (Y/N)": "...14",
    "Total deal value($m)": "1770",
    "Upfront value ($m)": "370",
    "Milestones/earnouts ($m)": "1400",
    "VC investment": "...14",
    "Therapy Area(s)": "Ophthalmology",
    "Drug type (biologic/small molecule/vaccine)": "...14",
    "Technology(s)": "Gene therapy",
    "Stage of lead product": "Phase III",
    "Lead product(s)": "RGX-314",
    "Indication(s)": "Wet AMD",
    "Mechanism of action": "AAV8-based, anti-VEGF gene therapy",
    "": "...14",
    "Potential first-in-class drug? (Y/N)": "...14",
    "Geographic remit of deal ":
      "Global (Regenxbio will participate in US marketing efforts)",
    "Deal structure": "...14",
    "Milestone dates": "...14",
    "Financial advisors": "...14",
    "Legal advisors": "...14",
    "Number of other interested parties (if M&A)": "...14",
    "Related FW content": "...14",
    "Post-deal updates": "...14"
  },
  {
    "Announcement Date": "...15",
    "Completion date": "...15",
    "Deal type": "...15",
    "Buyer/in-licenser/investor": "Amgen",
    "Country of Buyer": "...15",
    Region: "...15",
    "Target/partner/investee": "...15",
    "Country of Target": "...15",
    "Private/Public (Target)": "...15",
    "Premium paid (if Public)": "...15",
    "PE/VC backed (Y/N)": "...15",
    "Total deal value($m)": "...15",
    "Upfront value ($m)": "...15",
    "Milestones/earnouts ($m)": "...15",
    "VC investment": "...15",
    "Therapy Area(s)": "...15",
    "Drug type (biologic/small molecule/vaccine)": "...15",
    "Technology(s)": "...15",
    "Stage of lead product": "...15",
    "Lead product(s)": "...15",
    "Indication(s)": "...15",
    "Mechanism of action": "...15",
    "": "...15",
    "Potential first-in-class drug? (Y/N)": "...15",
    "Geographic remit of deal ": "...15",
    "Deal structure": "...15",
    "Milestone dates": "...15",
    "Financial advisors": "...15",
    "Legal advisors": "...15",
    "Number of other interested parties (if M&A)": "...15",
    "Related FW content": "...15",
    "Post-deal updates": "...15"
  },
  {
    "Announcement Date": "...16",
    "Completion date": "...16",
    "Deal type": "...16",
    "Buyer/in-licenser/investor": "Teva",
    "Country of Buyer": "...16",
    Region: "...16",
    "Target/partner/investee": "...16",
    "Country of Target": "...16",
    "Private/Public (Target)": "...16",
    "Premium paid (if Public)": "...16",
    "PE/VC backed (Y/N)": "...16",
    "Total deal value($m)": "...16",
    "Upfront value ($m)": "...16",
    "Milestones/earnouts ($m)": "...16",
    "VC investment": "...16",
    "Therapy Area(s)": "...16",
    "Drug type (biologic/small molecule/vaccine)": "...16",
    "Technology(s)": "...16",
    "Stage of lead product": "...16",
    "Lead product(s)": "...16",
    "Indication(s)": "...16",
    "Mechanism of action": "...16",
    "": "...16",
    "Potential first-in-class drug? (Y/N)": "...16",
    "Geographic remit of deal ": "...16",
    "Deal structure": "...16",
    "Milestone dates": "...16",
    "Financial advisors": "...16",
    "Legal advisors": "...16",
    "Number of other interested parties (if M&A)": "...16",
    "Related FW content": "...16",
    "Post-deal updates": "...16"
  },
  {
    "Announcement Date": "...17",
    "Completion date": "...17",
    "Deal type": "...17",
    "Buyer/in-licenser/investor": "Novo Nordisk",
    "Country of Buyer": "...17",
    Region: "...17",
    "Target/partner/investee": "...17",
    "Country of Target": "...17",
    "Private/Public (Target)": "...17",
    "Premium paid (if Public)": "...17",
    "PE/VC backed (Y/N)": "...17",
    "Total deal value($m)": "...17",
    "Upfront value ($m)": "...17",
    "Milestones/earnouts ($m)": "...17",
    "VC investment": "...17",
    "Therapy Area(s)": "...17",
    "Drug type (biologic/small molecule/vaccine)": "...17",
    "Technology(s)": "...17",
    "Stage of lead product": "...17",
    "Lead product(s)": "...17",
    "Indication(s)": "...17",
    "Mechanism of action": "...17",
    "": "...17",
    "Potential first-in-class drug? (Y/N)": "...17",
    "Geographic remit of deal ": "...17",
    "Deal structure": "...17",
    "Milestone dates": "...17",
    "Financial advisors": "...17",
    "Legal advisors": "...17",
    "Number of other interested parties (if M&A)": "...17",
    "Related FW content": "...17",
    "Post-deal updates": "...17"
  },
  {
    "Announcement Date": "...18",
    "Completion date": "...18",
    "Deal type": "...18",
    "Buyer/in-licenser/investor": "...18",
    "Country of Buyer": "...18",
    Region: "...18",
    "Target/partner/investee": "...18",
    "Country of Target": "...18",
    "Private/Public (Target)": "...18",
    "Premium paid (if Public)": "...18",
    "PE/VC backed (Y/N)": "...18",
    "Total deal value($m)": "...18",
    "Upfront value ($m)": "...18",
    "Milestones/earnouts ($m)": "...18",
    "VC investment": "...18",
    "Therapy Area(s)": "...18",
    "Drug type (biologic/small molecule/vaccine)": "...18",
    "Technology(s)": "...18",
    "Stage of lead product": "...18",
    "Lead product(s)": "...18",
    "Indication(s)": "...18",
    "Mechanism of action": "...18",
    "": "...18",
    "Potential first-in-class drug? (Y/N)": "...18",
    "Geographic remit of deal ": "...18",
    "Deal structure": "...18",
    "Milestone dates": "...18",
    "Financial advisors": "...18",
    "Legal advisors": "...18",
    "Number of other interested parties (if M&A)": "...18",
    "Related FW content": "...18",
    "Post-deal updates": "...18"
  },
  {
    "Announcement Date": "...19",
    "Completion date": "...19",
    "Deal type": "...19",
    "Buyer/in-licenser/investor": "Eli Lilly",
    "Country of Buyer": "...19",
    Region: "...19",
    "Target/partner/investee": "...19",
    "Country of Target": "...19",
    "Private/Public (Target)": "...19",
    "Premium paid (if Public)": "...19",
    "PE/VC backed (Y/N)": "...19",
    "Total deal value($m)": "...19",
    "Upfront value ($m)": "...19",
    "Milestones/earnouts ($m)": "...19",
    "VC investment": "...19",
    "Therapy Area(s)": "...19",
    "Drug type (biologic/small molecule/vaccine)": "...19",
    "Technology(s)": "...19",
    "Stage of lead product": "...19",
    "Lead product(s)": "...19",
    "Indication(s)": "...19",
    "Mechanism of action": "...19",
    "": "...19",
    "Potential first-in-class drug? (Y/N)": "...19",
    "Geographic remit of deal ": "...19",
    "Deal structure": "...19",
    "Milestone dates": "...19",
    "Financial advisors": "...19",
    "Legal advisors": "...19",
    "Number of other interested parties (if M&A)": "...19",
    "Related FW content": "...19",
    "Post-deal updates": "...19"
  },
  {
    "Announcement Date": "...20",
    "Completion date": "...20",
    "Deal type": "Tech development",
    "Buyer/in-licenser/investor": "Bayer",
    "Country of Buyer": "...20",
    Region: "...20",
    "Target/partner/investee": "Huma",
    "Country of Target": "...20",
    "Private/Public (Target)": "...20",
    "Premium paid (if Public)": "...20",
    "PE/VC backed (Y/N)": "...20",
    "Total deal value($m)": "...20",
    "Upfront value ($m)": "...20",
    "Milestones/earnouts ($m)": "...20",
    "VC investment": "...20",
    "Therapy Area(s)": "Oncology",
    "Drug type (biologic/small molecule/vaccine)": "...20",
    "Technology(s)": "AI for precision diagnostics",
    "Stage of lead product": "...20",
    "Lead product(s)": "-",
    "Indication(s)": "Lung cancer",
    "Mechanism of action": "...20",
    "": "...20",
    "Potential first-in-class drug? (Y/N)": "...20",
    "Geographic remit of deal ": "...20",
    "Deal structure": "...20",
    "Milestone dates": "...20",
    "Financial advisors": "...20",
    "Legal advisors": "...20",
    "Number of other interested parties (if M&A)": "...20",
    "Related FW content": "...20",
    "Post-deal updates": "...20"
  },
  {
    "Announcement Date": "...21",
    "Completion date": "...21",
    "Deal type": "...21",
    "Buyer/in-licenser/investor": "Allergan",
    "Country of Buyer": "...21",
    Region: "...21",
    "Target/partner/investee": "...21",
    "Country of Target": "...21",
    "Private/Public (Target)": "...21",
    "Premium paid (if Public)": "...21",
    "PE/VC backed (Y/N)": "...21",
    "Total deal value($m)": "...21",
    "Upfront value ($m)": "...21",
    "Milestones/earnouts ($m)": "...21",
    "VC investment": "...21",
    "Therapy Area(s)": "...21",
    "Drug type (biologic/small molecule/vaccine)": "...21",
    "Technology(s)": "...21",
    "Stage of lead product": "...21",
    "Lead product(s)": "...21",
    "Indication(s)": "...21",
    "Mechanism of action": "...21",
    "": "...21",
    "Potential first-in-class drug? (Y/N)": "...21",
    "Geographic remit of deal ": "...21",
    "Deal structure": "...21",
    "Milestone dates": "...21",
    "Financial advisors": "...21",
    "Legal advisors": "...21",
    "Number of other interested parties (if M&A)": "...21",
    "Related FW content": "...21",
    "Post-deal updates": "...21"
  },
  {
    "Announcement Date": "...22",
    "Completion date": "...22",
    "Deal type": "...22",
    "Buyer/in-licenser/investor": "Takeda",
    "Country of Buyer": "...22",
    Region: "...22",
    "Target/partner/investee": "...22",
    "Country of Target": "...22",
    "Private/Public (Target)": "...22",
    "Premium paid (if Public)": "...22",
    "PE/VC backed (Y/N)": "...22",
    "Total deal value($m)": "...22",
    "Upfront value ($m)": "...22",
    "Milestones/earnouts ($m)": "...22",
    "VC investment": "...22",
    "Therapy Area(s)": "...22",
    "Drug type (biologic/small molecule/vaccine)": "...22",
    "Technology(s)": "...22",
    "Stage of lead product": "...22",
    "Lead product(s)": "...22",
    "Indication(s)": "...22",
    "Mechanism of action": "...22",
    "": "...22",
    "Potential first-in-class drug? (Y/N)": "...22",
    "Geographic remit of deal ": "...22",
    "Deal structure": "...22",
    "Milestone dates": "...22",
    "Financial advisors": "...22",
    "Legal advisors": "...22",
    "Number of other interested parties (if M&A)": "...22",
    "Related FW content": "...22",
    "Post-deal updates": "...22"
  },
  {
    "Announcement Date": "...23",
    "Completion date": "...23",
    "Deal type": "...23",
    "Buyer/in-licenser/investor": "Bristol-Myers Squibb",
    "Country of Buyer": "...23",
    Region: "...23",
    "Target/partner/investee": "...23",
    "Country of Target": "...23",
    "Private/Public (Target)": "...23",
    "Premium paid (if Public)": "...23",
    "PE/VC backed (Y/N)": "...23",
    "Total deal value($m)": "...23",
    "Upfront value ($m)": "...23",
    "Milestones/earnouts ($m)": "...23",
    "VC investment": "...23",
    "Therapy Area(s)": "...23",
    "Drug type (biologic/small molecule/vaccine)": "...23",
    "Technology(s)": "...23",
    "Stage of lead product": "...23",
    "Lead product(s)": "...23",
    "Indication(s)": "...23",
    "Mechanism of action": "...23",
    "": "...23",
    "Potential first-in-class drug? (Y/N)": "...23",
    "Geographic remit of deal ": "...23",
    "Deal structure": "...23",
    "Milestone dates": "...23",
    "Financial advisors": "...23",
    "Legal advisors": "...23",
    "Number of other interested parties (if M&A)": "...23",
    "Related FW content": "...23",
    "Post-deal updates": "...23"
  },
  {
    "Announcement Date": "...24",
    "Completion date": "...24",
    "Deal type": "...24",
    "Buyer/in-licenser/investor": "Boehringer Ingelheim",
    "Country of Buyer": "...24",
    Region: "...24",
    "Target/partner/investee": "...24",
    "Country of Target": "...24",
    "Private/Public (Target)": "...24",
    "Premium paid (if Public)": "...24",
    "PE/VC backed (Y/N)": "...24",
    "Total deal value($m)": "...24",
    "Upfront value ($m)": "...24",
    "Milestones/earnouts ($m)": "...24",
    "VC investment": "...24",
    "Therapy Area(s)": "...24",
    "Drug type (biologic/small molecule/vaccine)": "...24",
    "Technology(s)": "...24",
    "Stage of lead product": "...24",
    "Lead product(s)": "...24",
    "Indication(s)": "...24",
    "Mechanism of action": "...24",
    "": "...24",
    "Potential first-in-class drug? (Y/N)": "...24",
    "Geographic remit of deal ": "...24",
    "Deal structure": "...24",
    "Milestone dates": "...24",
    "Financial advisors": "...24",
    "Legal advisors": "...24",
    "Number of other interested parties (if M&A)": "...24",
    "Related FW content": "...24",
    "Post-deal updates": "...24"
  },
  {
    "Announcement Date": "...25",
    "Completion date": "...25",
    "Deal type": "...25",
    "Buyer/in-licenser/investor": "Astellas",
    "Country of Buyer": "...25",
    Region: "...25",
    "Target/partner/investee": "...25",
    "Country of Target": "...25",
    "Private/Public (Target)": "...25",
    "Premium paid (if Public)": "...25",
    "PE/VC backed (Y/N)": "...25",
    "Total deal value($m)": "...25",
    "Upfront value ($m)": "...25",
    "Milestones/earnouts ($m)": "...25",
    "VC investment": "...25",
    "Therapy Area(s)": "...25",
    "Drug type (biologic/small molecule/vaccine)": "...25",
    "Technology(s)": "...25",
    "Stage of lead product": "...25",
    "Lead product(s)": "...25",
    "Indication(s)": "...25",
    "Mechanism of action": "...25",
    "": "...25",
    "Potential first-in-class drug? (Y/N)": "...25",
    "Geographic remit of deal ": "...25",
    "Deal structure": "...25",
    "Milestone dates": "...25",
    "Financial advisors": "...25",
    "Legal advisors": "...25",
    "Number of other interested parties (if M&A)": "...25",
    "Related FW content": "...25",
    "Post-deal updates": "...25"
  }
];
